# Generated by Django 3.0.5 on 2022-09-11 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('specialisation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number_of_beds', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.IntegerField()),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=4)),
                ('heart_rate', models.IntegerField()),
                ('pulse_oxymetry', models.DecimalField(decimal_places=2, max_digits=2)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.Doctor')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.Ward')),
            ],
        ),
    ]
