# Generated by Django 3.0.5 on 2022-09-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
